### ISSUE TITLE
Add issue template for bug reporting

### ISSUE THREAD

**Issue by johngerome** [RxCP/rxcp#145]
Reference
https://github.com/johngerome/js-sticky-table-headers/issues/new/choose

**Comment by saimaheshtaduri** [comment]
I can contribute, assign to me. Thanks

**Comment by johngerome** [comment]
@saimaheshtaduri  Sure, you can have It.
Please follow https://www.conventionalcommits.org/en/v1.0.0/ for the commit messages convention.

in this case, It would be `chore: <you commit message>` this will be the subject of your pull request as well.
Thanks

**Comment by johngerome** [comment]
@saimaheshtaduri I'll be assigning this to another 3 days from now. Let me know if you have any clarification I'll guide you through the process.

**Comment by gopivaibhav** [comment]
Hey @johngerome I am ready to work for this issue. Can you please assign me?

**Comment by gopivaibhav** [comment]
Please verify the [PR](https://github.com/RxCP/rxcp/pull/238) sent to clear this issue and do let me know if I wanna do some change in the template

**Comment by johngerome** [comment]
@gopivaibhav all good. I labeled your PR with `hacktoberfest-accepted`. Thanks again.
